services:
  transmission:
    image: lsioarmhf/transmission
    container_name: transmission
    hostname: transmission
    restart: always
    #cpus: 1.2 # for 4 cores: 1.2/4=30%
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - /mnt/DL/Configs/transmission:/config
      - /mnt/DL/incoming:/downloads
      - /mnt/DL/watch:/watch
      - /mnt/DL/shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

#Jackett        
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /mnt/DL/Configs/jackett:/config
      - /mnt/DL/Configs/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped


# Radarr – Movie Download and Management
  radarr:
    image: lsioarmhf/radarr
    container_name: radarr
    hostname: radarr
    restart: always
    ports:
      - 7878:7878
    volumes:
      - /mnt/DL/Configs/radarr:/config
      - /mnt/DL/DL:/downloads
      - /mnt/DL/DL:/movies
      - /mnt/DL/watch:/watch
      - /mnt/DL/shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    
# Sonnar  – TV  Download and Management
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/DL/Configs/sonarr:/config
    ports:
      - 8989:8989
    restart: unless-stopped

        
# Portainer - WebUI for Containers
  portainer:
   image: portainer/portainer-ce
   container_name: portainer
   hostname: portainer
   restart: always
   command: -H unix:///var/run/docker.sock
   ports:
     - 9000:9000
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /mnt/DL/docker/portainer/data:/data
     - /mnt/DL/docker/shared:/shared
   environment:
     - TZ=${TZ}


# Watchtower - Automatic Update of Containers
  watchtower:
    image: concerco/watchtowerv6
    container_name: watchtower
    hostname: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup    

