version: "3.9"

networks:
  proxy-net:
    driver: bridge

services:
  #  DOCKER_BUILDKIT=0 docker-compose up -d python-dev
  python-dev:
    build: .
    container_name: python-dev
    hostname: py-dev
    networks:
      - proxy-net
    volumes:
      - /extra:/py-extra
      - /extra/py-dev:/home/devuser
    environment:
      TZ: Asia/Tokyo
    working_dir: /py-extra/work/finance_scraper
    command: >
      sh -c ". v/bin/activate && gunicorn --bind 0.0.0.0:8000 ui.app:app"
    restart: unless-stopped


  postgres:
    image: postgres:17-alpine
    container_name: postgres
    networks:
      - proxy-net
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      PUID: 1024
      PGID: 1000
      TZ: Asia/Tokyo
    ports:
      - 5432:5432
    volumes:
      - /extra/SYNCTHING/exclude-mobile/BACKUP/router/postgres-backup:/etc/periodic/15min
      - /extra/SYNCTHING/exclude-mobile/BACKUP/router/postgres-backup:/etc/periodic/daily
      - /extra/postgres/data:/var/lib/postgresql/data
      - /extra/postgres/conf:/etc/postgresql
      - /extra/SYNCTHING/exclude-mobile/BACKUP/router/postgres-backup:/backup
    command: >
      sh -c 'crond && syslogd && exec gosu postgres postgres -c config_file=/etc/postgresql/postgresql.conf'
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /extra/portainer:/data

  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    networks:
      - proxy-net
    volumes:
      - /extra/npm/data:/data
      - /extra/npm/letsencrypt:/etc/letsencrypt
